# Generated by Django 5.1.2 on 2025-01-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('appearances', models.IntegerField()),
                ('saves', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('appearances', models.IntegerField()),
                ('saves', models.IntegerField()),
            ],
        ),
    ]
