# Generated by Django 5.1.2 on 2025-01-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='appearances',
        ),
        migrations.RemoveField(
            model_name='team',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='team',
            name='games',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='team',
            name='saves',
        ),
        migrations.AddField(
            model_name='team',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='ga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='gf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
